apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: aizqtktxy-python 
  janus-idp.io/tekton: aizqtktxy-python
  backstage.io/kubernetes-id: aizqtktxy-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aizqtktxy-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  